In [9]:
import numpy as np

In [10]:
arr1=np.array([])

In [11]:
type(arr1)

numpy.ndarray

In [12]:
l1=[]
l1

[]

In [13]:
my_list=[1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [14]:
a=np.array(my_list)
a

array([1, 2, 3, 4, 5])

In [15]:
type(a)

numpy.ndarray

In [16]:
my_list+[2,3]

[1, 2, 3, 4, 5, 2, 3]

In [17]:
a

array([1, 2, 3, 4, 5])

In [18]:
a.ndim

1

In [19]:
a.size

5

In [20]:
a.shape

(5,)

# Arrays

In [21]:
my_matrix=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
my_matrix
type(my_matrix)

list

In [22]:
b=np.array(my_matrix)

In [23]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
type(b)

numpy.ndarray

In [25]:
b.ndim

2

In [26]:
b.size

12

In [27]:
b.shape

(3, 4)

In [28]:
b.dtype

dtype('int64')

In [29]:
type(b)

numpy.ndarray

In [31]:
arr1=np.array([[[1,2,3],[4,5,6]] , [[7,8,9],[10,11,12]]])
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
arr1.shape

(2, 2, 3)

In [33]:
arr1.ndim

3

In [34]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
arr1[1][1][1]

np.int64(11)

In [36]:
arr1[1][0][1]

np.int64(8)

In [37]:
np.mean([1,2,3,45])

np.float64(12.75)

In [38]:
l1=[1,2,3,45]

In [39]:
import pandas as pd
l1=[1,2,3,45]
d1=pd.DataFrame(l1)
d1.mean()

0    12.75
dtype: float64

# built in methods

In [45]:
arr2=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
arr2.shape

(1, 4, 3)

In [47]:
arr2.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
desc_arr=np.sort(arr2.reshape(-1))[::-1]
desc_arr

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

# Arrange

In [49]:
list(range(10+1))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [50]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

# zeros and ones

In [53]:
np.zeros(3)

array([0., 0., 0.])

In [54]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [55]:
np.ones(3)

array([1., 1., 1.])

In [56]:
np.ones((2,5,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# linspace

In [57]:
import numpy as np

In [4]:
np.linspace(1,15)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [5]:
np.linspace(5,25,10,retstep=True)

(array([ 5.        ,  7.22222222,  9.44444444, 11.66666667, 13.88888889,
        16.11111111, 18.33333333, 20.55555556, 22.77777778, 25.        ]),
 np.float64(2.2222222222222223))

In [6]:
np.linspace(2,10,5,retstep=True)

(array([ 2.,  4.,  6.,  8., 10.]), np.float64(2.0))

np.linspace(0,25,retstep=True)

In [8]:
np.linspace(0,200,10)

array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
        88.88888889, 111.11111111, 133.33333333, 155.55555556,
       177.77777778, 200.        ])

In [9]:
np.linspace(0,200,10,retstep=True)

(array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
         88.88888889, 111.11111111, 133.33333333, 155.55555556,
        177.77777778, 200.        ]),
 np.float64(22.22222222222222))

 # Eye

In [10]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# broadcasting in an array

In [16]:

big_one=np.ones((3,4))
print(big_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
big_one.dtype

dtype('float64')

In [18]:
type(big_one)

numpy.ndarray

In [19]:
big_one*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [20]:
# the ability to access each and every of an array is known as broadcasting.


In [21]:
bigger_one=big_one*6-2
bigger_one

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [22]:
big_one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
bigger=np.array(big_one*5-3,dtype='int')
print(bigger)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [24]:
bigger.dtype

dtype('int64')

In [25]:
type(bigger)

numpy.ndarray

In [26]:
bigger.shape

(3, 4)

In [27]:
bigger//bigger

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
bigger

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [41]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
1/arr1[1:]

array([[[0.14285714, 0.125     , 0.11111111],
        [0.1       , 0.09090909, 0.08333333]]])

In [44]:
1/arr1[0:]

array([[[1.        , 0.5       , 0.33333333],
        [0.25      , 0.2       , 0.16666667]],

       [[0.14285714, 0.125     , 0.11111111],
        [0.1       , 0.09090909, 0.08333333]]])

In [60]:
arr1=np.arange(20)
1/arr1

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [59]:
import warnings
warnings.filterwarnings("ignore")

In [61]:
arr=np.arange(4)

In [62]:
arr

array([0, 1, 2, 3])

In [63]:
arr+arr

array([0, 2, 4, 6])

In [64]:
arr**arr

array([ 1,  1,  4, 27])

# use of copy function

In [65]:
arr1=np.arange(0,19)

In [66]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [67]:
arr1[7]=100

In [68]:
arr1

array([  0,   1,   2,   3,   4,   5,   6, 100,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18])

In [69]:
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [75]:
arr1

array([  0,   1,   2,   3,   4,   5,   6, 233,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18])

In [76]:
arr2

array([  0,   1,   2,   3,   4,   5,   6, 233,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18])

In [77]:
arr2=arr1

In [78]:
arr2

array([  0,   1,   2,   3,   4,   5,   6, 233,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18])

In [85]:
array=np.arange(20)

In [86]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [87]:
arr3=arr1.copy()

In [88]:
arr3

array([  0,   1,   2,   3,   4,   5,   6, 233,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18])

In [92]:
print(arr3)
print(arr1)

[  0   1   2   3   4   5   6 233   8   9 100 100 100 100 100 100 100 100
 100]
[  0   1   2   3   4   5   6 233   8   9  10  11  12  13  14  15  16  17
  18]


In [93]:
arr3[10:]=100
arr3

array([  0,   1,   2,   3,   4,   5,   6, 233,   8,   9, 100, 100, 100,
       100, 100, 100, 100, 100, 100])

In [94]:
arr1

array([  0,   1,   2,   3,   4,   5,   6, 233,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18])

 # random number generation

In [95]:
np.random.rand()

0.15316196247000513

In [96]:
np.random.rand(10)

array([0.71780397, 0.03182878, 0.0251049 , 0.50279521, 0.00804082,
       0.16474066, 0.04260787, 0.38958702, 0.65176471, 0.58206432])

In [97]:
np.random.rand(5,2)

array([[0.99862604, 0.3078046 ],
       [0.36603645, 0.7038665 ],
       [0.49599314, 0.95494109],
       [0.68939264, 0.30891612],
       [0.28213276, 0.89224826]])

In [99]:
arr1=np.random.randn(50)

In [100]:
arr1

array([ 1.08408779, -0.69275423,  1.86702115,  1.26641717, -0.29770354,
        2.00563227,  0.56498315, -0.36540195,  1.38838273,  0.76459234,
       -1.70160183,  0.45143704, -1.80351578,  0.00273225,  0.28978609,
       -1.5743932 ,  0.12872939, -1.01404388,  1.74606745, -0.0968042 ,
        0.0495916 ,  0.49392126, -0.45043931,  0.60159757,  2.16991925,
       -0.43741895,  0.20791621,  0.54884486, -1.56251684,  0.25215422,
        1.86403744,  0.55484234, -0.59259273, -1.68514315, -2.67422941,
       -0.5606756 ,  0.8265477 ,  1.76360927,  0.18995612, -0.96408681,
        0.29025979, -0.03232971,  0.50583508,  0.49370196,  0.11687664,
       -0.58584804, -0.49160088, -0.25669896,  2.23682329, -1.33613322])

In [101]:
np.mean(arr1)

np.float64(0.1110074236173971)

In [102]:
np.median(arr1)

np.float64(0.15934275784545027)

In [104]:
np.std(arr1)

np.float64(1.113725072593627)

In [105]:
 # randint
np.random.randint(1,100)

74

In [138]:
np.random.randint(1,7)


1

In [139]:
arr2=np.random.randint(1,100,20)

In [140]:
arr2

array([48, 41, 79, 76, 48, 66, 79, 12, 51, 56, 16, 10, 33, 12, 13, 62, 14,
        1, 60, 39], dtype=int32)

In [141]:
arr2.max()

np.int32(79)

In [142]:
arr2.min()

np.int32(1)

In [143]:
arr2.argmax()

np.int64(2)

In [144]:
arr2.argmin()

np.int64(17)

In [145]:
ranarr=np.random.randint(0,100,10)
ranarr

array([23, 39, 32, 19, 54, 81, 91, 66, 35,  7], dtype=int32)

In [146]:
ranarr.argmax()

np.int64(6)

In [147]:
ranarr.argmin()

np.int64(9)

In [148]:
ranarr.min()

np.int32(7)

In [149]:
ranarr.max()

np.int32(91)

In [150]:
# indexing and selection
arr=np.arange(10,100,5)

In [151]:
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [152]:
len(arr)

18

In [153]:
arr[-1]

np.int64(95)

In [154]:
arr[9]

np.int64(55)

In [155]:
arr[1:11:2]

array([15, 25, 35, 45, 55])

 # filtering

In [156]:

arr=np.array([1,2,1010,4,108,18,71,610])
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [157]:
arr<100

array([ True,  True, False,  True, False,  True,  True, False])

In [158]:
np.where(arr>100)

(array([2, 4, 7]),)

In [159]:
arr[5]

np.int64(18)

In [160]:
np.where(arr<100)

(array([0, 1, 3, 5, 6]),)

In [161]:
arr[np.where(arr<100)]

array([ 1,  2,  4, 18, 71])

In [162]:
arr[np.where(arr>100)]

array([1010,  108,  610])

In [163]:
np.where(arr<100)

(array([0, 1, 3, 5, 6]),)

In [164]:
np.where(arr==100)

(array([], dtype=int64),)

In [165]:
arr_2d=np.array(([1,2,3],[12,15,18],[64,96,128]))
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [166]:
arr_2d[2,1]

np.int64(96)

In [167]:
l1=[1,2,3,4,5]
l1

[1, 2, 3, 4, 5]

In [168]:
l1[:3]

[1, 2, 3]